version: '3.5'
services:
  guacamole:
    image: guacamole/guacamole:latest
    depends_on:
      - guacd
      - guacdb
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacdb
      POSTGRES_USER: guac
      POSTGRES_DATABASE: guac
      POSTGRES_PASSWORD: {{DB_PASS}} 
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped

  guacdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: guac
      POSTGRES_USER: guac
      POSTGRES_PASSWORD: {{DB_PASS}} 
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    restart: unless-stopped

  api:
    image: nickadam/ordig:1.0
    user: node
    working_dir: /home/node/app
    command: bash -c 'while true; do npm start; done'
    environment:
      GU_NAME: {{GU_NAME}}
      WG_NAME: {{WG_NAME}}
      WG_IP: {{WG_IP}}
      WG_POOL: {{WG_POOL}}
      WG_NAMESPACE: {{WG_NAMESPACE}}
      WG_NAMESERVER: {{WG_NAMESERVER}}
      WG_PORT: {{WG_PORT}}
      WG_ENDPOINT: {{WG_ENDPOINT}}
      WG_ALLOWED: {{WG_ALLOWED}}
      WG_SERVER_API_KEY: {{WG_SERVER_API_KEY}}
      WG_CLIENT_API_KEY: {{WG_CLIENT_API_KEY}}
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - type: volume
        source: data
        target: /data
  proxy:
    image: caddy/caddy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: ./public
        target: /var/www/html/public
      - type: volume
        source: caddy
        target: /data
volumes:
  data: {}
  caddy: {}

